spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}

kakao:
  redirect-uri: ${REDIRECT_URI}
  key:
    client-id: ${CLIENT_ID}